chore: add GH template boilerplate
ChainSafe/filecoin-common-node-api pull request #43
Opened 2024-10-04 12:50 UTC by LesnyRumcajs

Changes:
- Added some boilerplate to make this repo more of a first-class citizen

2024-10-04 14:52 UTC, LesnyRumcajs commented on README.md
> -- [`cna-util`](src/test-suite/README.md)
this was wrong.

2024-10-04 14:53 UTC, LesnyRumcajs commented on src/test-suite/src/main.rs
> +    expect_test::expect_file!["../API.md"].assert_eq(&cna_util::markdown(
Moved to files that would more likely be understood as auto-generated (and it's easier to put it to prettify)

2024-10-04 19:06 UTC, ansermino requested changes
Please update issue template naming as per https://github.com/ChainSafe/forest/pull/4846

2024-10-04 19:06 UTC, ansermino commented on .github/ISSUE_TEMPLATE/task.md
> +about: "[internal] A specific, actionable unit of work"
```suggestion
about: "[Internal] A specific, actionable unit of work"
```

2024-10-04 19:06 UTC, ansermino commented on .github/ISSUE_TEMPLATE/epic.md
> +about: [Internal] Larger chunk of work that can be broken down into a smaller tasks
```suggestion
about: "[Internal] Larger chunk of work that can be broken down into smaller tasks"
```

2024-10-07 23:27 UTC, ansermino approved these changes

2024-10-08 08:26 UTC, merged